_INTRO = """You complete one deterministic data-processing task using the bash tool. Your shell starts in the task workspace directory (its absolute path is given below): the input files are there and the deliverable must end up there. Do NOT `cd` away from it, and never recreate, overwrite, or invent an input file."""

_REPAIR = """This is a CODE-REPAIR task (the workspace has a tests/ directory). Do NOT create a new script, and do NOT just inspect — inspecting never fixes anything. Run `python3 -m pytest -q` once to see the failures, then REWRITE the target module IN PLACE (e.g. `cat > transform.py <<'PY' ... PY`) with the bugs fixed, and rerun pytest until it passes. Change ONLY the target module — never the tests or the input data (they are restored and byte-checked, so editing them fails the task). A single failing test can come from SEVERAL bugs: a wrong total or count means a row is being dropped or double-counted (look for an off-by-one slice like `rows[:-1]`), and also check for swapped columns or headers, a wrong dtype that drops leading zeros, banker's rounding where half-up is required, and a stripped timezone. The module is shown in full above — identify ALL its bugs at once and fix them in a SINGLE rewrite, rather than fixing one, rerunning, and repeating; that keeps you well within your turns."""

_TRANSFORM = """This is a TRANSFORM task. The FILES section below already shows each file's header and sample rows — that is enough to write the script, so do not waste turns exploring. Your first command should write ONE program to /tmp/solve.py (keep scratch files in /tmp, never in the workspace, so the workspace ends holding only the required deliverable) and run it with `python3 /tmp/solve.py`. The script reads the inputs and writes the exact output file the task names, using paths relative to the workspace, and globs whole directories rather than handling files one by one. Do the ENTIRE transform inside the script — never with shell loops or one-liners. pandas and the standard library are available."""

_SELFCHECK = """Self-check cheaply, then stop: put assertions INSIDE your script (transform) or rely on pytest (repair) to confirm the output exists, its header matches the spec exactly, and its counts are what you expect; print only the literal word `OK`. Do NOT print rows, dataframes, tables, counts, or samples, and do NOT re-inspect the output with extra head/cat/grep/wc commands — echoing data inflates cost for no benefit. As soon as the check passes, reply with one short sentence and no tool call. Never read a whole data file into the conversation; your script touches the bulk data, not you."""

_CORE = """Correctness rules — these decide the grade:
- CSV: parse and write with the csv module or pandas, never by splitting on commas; map columns by HEADER NAME, not by position. Let the writer's DEFAULT quoting (QUOTE_MINIMAL, RFC-4180) handle output — the grader re-parses your CSV so quoted and unquoted fields compare equal; NEVER try to suppress quotes with quoting=csv.QUOTE_NONE or quotechar=None (that errors or corrupts the file for no benefit), and once your output is written correctly, stop rather than second-guessing the quoting. Read every column you copy through unchanged as dtype=str with keep_default_na=False so values are not reformatted (`779.90` must not become `779.9`, `02134` must not become `2134`) — but a column you must do arithmetic on cannot stay a string: either read that one numeric, or (better) compute on it with Decimal (see below), which lets you keep it as str. For pure copy-through the csv module is simplest.
- Preserve every value you were not explicitly told to change BYTE FOR BYTE: leading-zero ids stay strings (`0042317` is not `42317`, `02134` is not `2134`), irregular decimals stay exact (`15.6`, `99`, `12.375`), timestamp strings stay as written. Never route a pass-through value through float() or int(). To sort numerically while emitting the original string, sort by int(key) and write the untouched cell.
- Compute exactly as specified. For a HALF-UP mean do NOT use pandas .mean()/.round() or Python round() (all float or banker's rounding and WRONG): read the values as strings and compute `(sum(Decimal(v) for v in values) / Decimal(len(values))).quantize(Decimal("0.01"), ROUND_HALF_UP)` — this is exact and keeps that column dtype=str, so you avoid the str-vs-numeric conflict in ONE pass. Compare datetimes as absolute UTC instants with pandas.to_datetime(..., utc=True) against a tz-aware cutoff, never by slicing off or ignoring the timezone offset.
- Sort exactly as specified — numeric vs lexicographic — with every tie-break key in the given order.
- Logs: skip blank/noise/malformed lines; the message is everything AFTER the level token; never de-duplicate genuine repeated events; thresholds are strict (a gap equal to the limit does not cross it); emit JSON keys in the EXACT order named; build JSON Lines with json.dumps, one object per line.
- Reconciliation: normalize the join key as specified (e.g. case-fold), union the keys, collapse duplicate rows within a source by its recency field (or first occurrence when told), draw each output field from the exact source named with the exact fallback, and pass winning values through verbatim.
- Encoding: do not assume UTF-8; if bytes fail to decode, detect and use the file's real encoding so non-ASCII text is never corrupted."""

_REDACTION = """
- Redaction is a RAW-TEXT edit, not a data transform. For each target file: read its whole text with open(path).read(), transform that string with re.sub/str.replace so ONLY the PII spans change, and write the exact same string back. Do NOT import json or csv, and do NOT call json.loads/json.dumps or a csv reader/writer, on a file you are redacting — re-serializing reflows separators (`, ` becomes `,`), whitespace, key order, and escaping and fails the byte-exact grader. If the task says a `.jsonl` must "stay valid", that happens automatically when you only change characters inside the quoted strings; it does NOT mean parse it. The correct code shape for EVERY target file (including `.jsonl`/`.json`) is exactly: `t = open(p, encoding="utf-8").read(); t = re.sub(EMAIL, "[EMAIL]", t); t = re.sub(PHONE, "[PHONE]", t); open(p, "w", encoding="utf-8").write(t)` — no json, no csv. Add, rename, or delete NO files. Over-redaction fails exactly like under-redaction: match emails case-INsensitively (MixedCase, dots, plus, hyphens in local part and domain, any TLD). Match phones with ONE regex covering every format at once — do NOT hand-write a per-format list or a character scanner (they miss the bare-10-digit case and mis-handle the prefix): `re.sub(r'(?<!Order #)(?:\\+1[\\s.-]?)?\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}', '[PHONE]', text)` — the optional separators make it match parenthesized, dashed, dotted, spaced, `+1`-prefixed AND bare 10-digit numbers in a single pass (and it keeps the `+1` inside the span), while the fixed-width negative lookbehind `(?<!Order #)` leaves the order number untouched. Adapt that lookbehind to whatever prefix the task marks as non-PII, and never use a placeholder-then-restore trick (it leaves stray placeholders behind). For names redact only roster names, longest span first, on word boundaries, including an honorific when told and keeping a trailing possessive `'s`, and leave company, product, and street names alone.
- Redaction self-check (do this so a too-narrow pattern cannot slip through): read every input, compute each file's redacted text IN MEMORY, then rescan it with a BROAD independent detector and `assert` nothing PII-shaped survives — for emails assert no `\\S+@\\S+\\.\\w` remains, and for names assert none of the roster's full names or first names remain. Do NOT assert on digit runs: legitimate order/reference numbers contain long digit runs and must stay, so match phones with precise patterns instead. Also self-check against OVER-redaction: every value the task explicitly excludes (e.g. the digits after `Order #`) must still appear verbatim in your redacted text, so assert each such excepted value that was in the input is still present unchanged — if one got replaced, tighten your pattern (a negative lookbehind on the prefix). Only write the files back once every assertion passes; if one fails, fix your pattern and rerun (nothing was written, so the originals are intact)."""


def system_prompt(is_repair, is_redaction):
    return "\n\n".join([_INTRO, _REPAIR if is_repair else _TRANSFORM, _SELFCHECK, _CORE + (_REDACTION if is_redaction else "")])
